# Generated by Django 6.1 on 2026-08-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('idActividad', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('objetivos', models.TextField()),
                ('instrucciones', models.TextField()),
                ('nivel_dificultad', models.CharField(max_length=20)),
                ('recursos_multimedia', models.CharField(max_length=255)),
                ('frecuencia', models.CharField(max_length=45)),
                ('duracion', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('creado_por', models.IntegerField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prevenapp.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('nivel_educativo', models.CharField(max_length=45)),
                ('eps', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=255)),
                ('rh', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prevenapp.rol')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionActividad',
            fields=[
                ('idParticipacion_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prevenapp.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prevenapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialChatbot',
            fields=[
                ('idHistorial_chat', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prevenapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('idContacto_Emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prevenapp.usuario')),
            ],
        ),
    ]
