# Generated by Django 6.1 on 2026-08-28 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_preven_app', '0002_remove_horario_profesional_profesional_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('objetivos', models.TextField(blank=True, null=True)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('nivel_dificultad', models.CharField(blank=True, max_length=50, null=True)),
                ('recursos_multimedia', models.CharField(blank=True, max_length=255, null=True)),
                ('frecuencia', models.CharField(blank=True, max_length=50, null=True)),
                ('duracion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('idRol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20)),
                ('credencial_profesional', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_preven_app.especialidad')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('num_citas', models.IntegerField(default=1)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='app_prevenapp.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Sala_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_chat', to='app_prevenapp.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=45)),
                ('apellidos', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(max_length=20)),
                ('eps', models.CharField(max_length=45)),
                ('contrasena', models.CharField(max_length=255)),
                ('rh', models.CharField(max_length=10)),
                ('estado', models.CharField(max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app_prevenapp.rol')),
            ],
        ),
        migrations.AddField(
            model_name='profesional',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to='app_prevenapp.usuario'),
        ),
        migrations.CreateModel(
            name='ParticipacionActividad',
            fields=[
                ('idParticipacion_actividad', models.AutoField(primary_key=True, serialize=False)),
                ('resultado', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='app_prevenapp.actividad')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_actividad', to='app_prevenapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialChatbot',
            fields=[
                ('idHistorial_chat', models.AutoField(primary_key=True, serialize=False)),
                ('pregunta', models.TextField()),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_chatbot', to='app_prevenapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('idContacto_Emergencia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='app_prevenapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to='app_prevenapp.profesional')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to='app_prevenapp.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_prevenapp.usuario'),
        ),
    ]
