# Generated by Django 6.1 on 2026-08-24 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prevenapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='app_prevenapp.categoria'),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='creado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades_creadas', to='app_prevenapp.usuario'),
        ),
        migrations.AlterField(
            model_name='contactoemergencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='app_prevenapp.usuario'),
        ),
        migrations.AlterField(
            model_name='historialchatbot',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_chatbot', to='app_prevenapp.usuario'),
        ),
        migrations.AlterField(
            model_name='participacionactividad',
            name='actividad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones', to='app_prevenapp.actividad'),
        ),
        migrations.AlterField(
            model_name='participacionactividad',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_actividad', to='app_prevenapp.usuario'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='app_prevenapp.rol'),
        ),
    ]
