# Generated by Django 6.1 on 2026-08-28 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prevenapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_prevenapp.categoria'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='nombre',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
