# Generated by Django 6.1 on 2026-08-24 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_preven_app', '0002_remove_horario_profesional_profesional_and_more'),
        ('app_prevenapp', '0002_alter_actividad_categoria_alter_actividad_creado_por_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='creado_por',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='duracion',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='frecuencia',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='instrucciones',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='nivel_dificultad',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='objetivos',
        ),
        migrations.RemoveField(
            model_name='actividad',
            name='recursos_multimedia',
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento_identidad', models.CharField(max_length=20)),
                ('credencial_profesional', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Disponible', max_length=20)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_preven_app.especialidad')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_profesional', to='app_prevenapp.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Horario_profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_semana', models.CharField(max_length=100)),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('num_citas', models.IntegerField(default=1)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='app_prevenapp.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_paciente', to='app_prevenapp.usuario')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_medico', to='app_prevenapp.profesional')),
            ],
        ),
        migrations.CreateModel(
            name='Sala_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salas_chat', to='app_prevenapp.profesional')),
            ],
        ),
    ]
