# Generated by Django 6.1 on 2026-08-24 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_preven_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario_profesional',
            name='profesional',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='especialidad',
        ),
        migrations.RemoveField(
            model_name='profesional',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='sala_chat',
            name='profesional',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='Horario_profesional',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
        migrations.DeleteModel(
            name='Profesional',
        ),
        migrations.DeleteModel(
            name='Sala_chat',
        ),
    ]
