# Generated by Django 6.1 on 2026-08-30 23:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('idRecurso', models.AutoField(primary_key=True, serialize=False)),
                ('Titulo', models.CharField(max_length=100)),
                ('Descripcion', models.TextField()),
                ('Tipo', models.CharField(max_length=45)),
                ('Fecha', models.DateField()),
                ('Creado_por', models.IntegerField()),
                ('Categoria_idCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_alejandra.categoria')),
            ],
        ),
    ]
